site_name: TMultimodal

pages:
    - Home: index.md
    - Conceptos: conceptos.md
    - Incoterms: incoterm.md
    - Importaciòn: importacion.md
    - Exportacion: exportacion.md
#theme: 'custom_theme'
